### ISSUE TITLE
Image is torn & mirrored after Pre-aligment

### ISSUE THREAD

**Issue by J-MHF** [jomjol/water-meter-system-complete#46]
Hi, 

the image is torn and also mirrored in some cases after the Pre alignment. I tried different angles in the config.ini and also used both docker versions on my Pi 4 ( raspi-rolling and raspi-latest). I tried different test pictures from URLs. 

It seems like i get some OK pictures if i choose around 220° in the config, which is weird.
If i choose 0° (which should be right) or 180° the preview (&full) is complety torn
  
Is there something else I could have probably done wrong? Btw I am a total beginner in this.

Great work and thank you in advance
Best regards

![2020-03-20-155400_1920x1080_scrot](https://user-images.githubusercontent.com/58692944/77181156-334fe200-6acb-11ea-83fe-41303405c55b.png)

![2020-03-20-181101_1920x1080_scrot](https://user-images.githubusercontent.com/58692944/77188540-71063800-6ad6-11ea-827e-5920b231eb08.png)

**Comment by jomjol** [comment]
A torne image is a clear signature of not correct found reference structures. In this case the position is arbitrary and the image rotation and correction is totally of. Try to use unique part of the image, ideally arranged in a triangular position and not affected by reflections.
Maybe you are still using the default references. I do not recommend to do so, because if the image is slightly changed (e.g. distance of camera to water meter, ...) this could cause problems.
Try to create your own structures. I have created a web-application for this: 
http://wasserzaehler.ignorelist.com/
There you will be guided through creatin your own settings.
Let me know, if you still have problems, then I will help you personally.
Best regards, jomjol

**Comment by J-MHF** [comment]
> 
> 
> A torne image is a clear signature of not correct found reference structures. In this case the position is arbitrary and the image rotation and correction is totally of. Try to use unique part of the image, ideally arranged in a triangular position and not affected by reflections.
> Maybe you are still using the default references. I do not recommend to do so, because if the image is slightly changed (e.g. distance of camera to water meter, ...) this could cause problems.
> Try to create your own structures. I have created a web-application for this:
> http://wasserzaehler.ignorelist.com/
> There you will be guided through creatin your own settings.
> Let me know, if you still have problems, then I will help you personally.
> Best regards, jomjol

Hi jomjol, 
it worked out pretty well after I uesed the custom references. 
Thank you very much for your support.
I will try to use your web-application as well in the future :)

Best regards
J-MHF

**Comment by jomjol** [comment]
Solved
